from datetime import date

from app_movie.models import Movie, Play
from app_people.models import Person

Play.objects.all().delete()
Movie.objects.all().delete()
Person.objects.all().delete()

# first selection

p2 = Person.objects.create(name="Anya Taylor-Joy", birthdate=date(1996, 4, 16))
p3 = Person.objects.create(name="Keanu Reeves", birthdate=date(1964, 9, 2))
p4 = Person.objects.create(name="Jean Gabin", birthdate=date(1904, 5, 17))
p5 = Person.objects.create(name="Chase Infiniti", birthdate=date(2000, 5, 5))
p6 = Person.objects.create(name="Arnold Schwarzenegger")

# --- Christopher Nolan ---

nolan = Person.objects.create(name="Christopher Nolan", birthdate=date(1970, 7, 30))

christian_bale = Person.objects.create(name="Christian Bale",       birthdate=date(1974,  1, 30))
michael_caine  = Person.objects.create(name="Michael Caine",        birthdate=date(1933,  3, 14))
gary_oldman    = Person.objects.create(name="Gary Oldman",          birthdate=date(1958,  3, 21))
tom_hardy      = Person.objects.create(name="Tom Hardy",            birthdate=date(1977,  9, 15))
joseph_gl      = Person.objects.create(name="Joseph Gordon-Levitt", birthdate=date(1981,  2, 17))
anne_hathaway  = Person.objects.create(name="Anne Hathaway",        birthdate=date(1982, 11, 12))
cillian_murphy = Person.objects.create(name="Cillian Murphy",       birthdate=date(1976,  5, 25))
kenneth_b      = Person.objects.create(name="Kenneth Branagh",      birthdate=date(1960, 12, 10))
matt_damon     = Person.objects.create(name="Matt Damon",           birthdate=date(1970, 10,  8))

guy_pearce  = Person.objects.create(name="Guy Pearce",       birthdate=date(1967, 10,  5))
carrie_moss = Person.objects.create(name="Carrie-Anne Moss", birthdate=date(1967,  8, 21))
joe_panto   = Person.objects.create(name="Joe Pantoliano",   birthdate=date(1951,  9, 12))
memento = Movie.objects.create(title="Memento", year=2000, duration=113, director=nolan)
Play.objects.create(movie=memento, actor=guy_pearce,  character="Leonard Shelby")
Play.objects.create(movie=memento, actor=carrie_moss, character="Natalie")
Play.objects.create(movie=memento, actor=joe_panto,   character="Teddy")

liam_neeson  = Person.objects.create(name="Liam Neeson",  birthdate=date(1952,  6,  7))
katie_holmes = Person.objects.create(name="Katie Holmes", birthdate=date(1978, 12, 18))
batman_begins = Movie.objects.create(title="Batman Begins", year=2005, duration=140, director=nolan)
Play.objects.create(movie=batman_begins, actor=christian_bale, character="Bruce Wayne / Batman")
Play.objects.create(movie=batman_begins, actor=michael_caine,  character="Alfred Pennyworth")
Play.objects.create(movie=batman_begins, actor=liam_neeson,    character="Ra's al Ghul")
Play.objects.create(movie=batman_begins, actor=gary_oldman,    character="Jim Gordon")
Play.objects.create(movie=batman_begins, actor=katie_holmes,   character="Rachel Dawes")

hugh_jackman = Person.objects.create(name="Hugh Jackman",       birthdate=date(1968, 10, 12))
scarlett_j   = Person.objects.create(name="Scarlett Johansson", birthdate=date(1984, 11, 22))
prestige = Movie.objects.create(title="The Prestige", year=2006, duration=130, director=nolan)
Play.objects.create(movie=prestige, actor=christian_bale, character="Alfred Borden")
Play.objects.create(movie=prestige, actor=hugh_jackman,   character="Robert Angier")
Play.objects.create(movie=prestige, actor=scarlett_j,     character="Olivia Wenscombe")
Play.objects.create(movie=prestige, actor=michael_caine,  character="Cutter")

heath_ledger  = Person.objects.create(name="Heath Ledger",  birthdate=date(1979,  4,  4), is_alive=False)
aaron_eckhart = Person.objects.create(name="Aaron Eckhart", birthdate=date(1968,  3, 12))
dark_knight = Movie.objects.create(title="The Dark Knight", year=2008, duration=152, director=nolan)
Play.objects.create(movie=dark_knight, actor=christian_bale, character="Bruce Wayne / Batman")
Play.objects.create(movie=dark_knight, actor=heath_ledger,   character="The Joker")
Play.objects.create(movie=dark_knight, actor=aaron_eckhart,  character="Harvey Dent / Two-Face")
Play.objects.create(movie=dark_knight, actor=michael_caine,  character="Alfred Pennyworth")
Play.objects.create(movie=dark_knight, actor=gary_oldman,    character="Jim Gordon")

leo_dicaprio = Person.objects.create(name="Leonardo DiCaprio", birthdate=date(1974, 11, 11))
elliot_page  = Person.objects.create(name="Elliot Page",       birthdate=date(1987,  2, 21))
ken_watanabe = Person.objects.create(name="Ken Watanabe",      birthdate=date(1959, 10, 21))
inception = Movie.objects.create(title="Inception", year=2010, duration=148, director=nolan)
Play.objects.create(movie=inception, actor=leo_dicaprio, character="Cobb")
Play.objects.create(movie=inception, actor=joseph_gl,    character="Arthur")
Play.objects.create(movie=inception, actor=elliot_page,  character="Ariadne")
Play.objects.create(movie=inception, actor=tom_hardy,    character="Eames")
Play.objects.create(movie=inception, actor=ken_watanabe, character="Saito")

dk_rises = Movie.objects.create(title="The Dark Knight Rises", year=2012, duration=164, director=nolan)
Play.objects.create(movie=dk_rises, actor=christian_bale, character="Bruce Wayne / Batman")
Play.objects.create(movie=dk_rises, actor=tom_hardy,      character="Bane")
Play.objects.create(movie=dk_rises, actor=anne_hathaway,  character="Selina Kyle / Catwoman")
Play.objects.create(movie=dk_rises, actor=joseph_gl,      character="John Blake")
Play.objects.create(movie=dk_rises, actor=gary_oldman,    character="Jim Gordon")

matthew_mc = Person.objects.create(name="Matthew McConaughey", birthdate=date(1969, 11,  4))
jessica_c  = Person.objects.create(name="Jessica Chastain",    birthdate=date(1977,  3, 24))
interstellar = Movie.objects.create(title="Interstellar", year=2014, duration=169, director=nolan)
Play.objects.create(movie=interstellar, actor=matthew_mc,    character="Cooper")
Play.objects.create(movie=interstellar, actor=anne_hathaway, character="Dr. Brand")
Play.objects.create(movie=interstellar, actor=jessica_c,     character="Murph (adulte)")
Play.objects.create(movie=interstellar, actor=michael_caine, character="Prof. Brand")
Play.objects.create(movie=interstellar, actor=matt_damon,    character="Dr. Mann")

fionn_w      = Person.objects.create(name="Fionn Whitehead", birthdate=date(1997,  7, 28))
mark_rylance = Person.objects.create(name="Mark Rylance",    birthdate=date(1960,  1, 18))
dunkirk = Movie.objects.create(title="Dunkirk", year=2017, duration=106, director=nolan)
Play.objects.create(movie=dunkirk, actor=fionn_w,        character="Tommy")
Play.objects.create(movie=dunkirk, actor=mark_rylance,   character="Mr. Dawson")
Play.objects.create(movie=dunkirk, actor=tom_hardy,      character="Farrier")
Play.objects.create(movie=dunkirk, actor=cillian_murphy, character="Shivering Soldier")
Play.objects.create(movie=dunkirk, actor=kenneth_b,      character="Commander Bolton")

jd_washington = Person.objects.create(name="John David Washington", birthdate=date(1984,  7, 28))
robert_p      = Person.objects.create(name="Robert Pattinson",      birthdate=date(1986,  5, 13))
elizabeth_d   = Person.objects.create(name="Elizabeth Debicki",     birthdate=date(1990,  8, 24))
dimple_k      = Person.objects.create(name="Dimple Kapadia",        birthdate=date(1957,  6,  8))
tenet = Movie.objects.create(title="Tenet", year=2020, duration=150, director=nolan)
Play.objects.create(movie=tenet, actor=jd_washington, character="The Protagonist")
Play.objects.create(movie=tenet, actor=robert_p,      character="Neil")
Play.objects.create(movie=tenet, actor=elizabeth_d,   character="Kat")
Play.objects.create(movie=tenet, actor=kenneth_b,     character="Andrei Sator")
Play.objects.create(movie=tenet, actor=dimple_k,      character="Priya Singh")

emily_blunt   = Person.objects.create(name="Emily Blunt",       birthdate=date(1983,  2, 23))
rdj           = Person.objects.create(name="Robert Downey Jr.", birthdate=date(1965,  4,  4))
florence_pugh = Person.objects.create(name="Florence Pugh",     birthdate=date(1996,  1,  3))
oppenheimer = Movie.objects.create(title="Oppenheimer", year=2023, duration=180, director=nolan)
Play.objects.create(movie=oppenheimer, actor=cillian_murphy, character="J. Robert Oppenheimer")
Play.objects.create(movie=oppenheimer, actor=emily_blunt,    character="Katherine Oppenheimer")
Play.objects.create(movie=oppenheimer, actor=matt_damon,     character="Leslie Groves")
Play.objects.create(movie=oppenheimer, actor=rdj,            character="Lewis Strauss")
Play.objects.create(movie=oppenheimer, actor=florence_pugh,  character="Jean Tatlock")

# --- James Bond (Craig era) ---

daniel_craig = Person.objects.create(name="Daniel Craig", birthdate=date(1968, 3, 2))

martin_campbell = Person.objects.create(name="Martin Campbell",    birthdate=date(1943, 10, 24))
marc_forster    = Person.objects.create(name="Marc Forster",       birthdate=date(1969, 11, 30))
sam_mendes      = Person.objects.create(name="Sam Mendes",         birthdate=date(1965,  8,  1))
cary_fukunaga   = Person.objects.create(name="Cary Joji Fukunaga", birthdate=date(1977,  7, 10))

casino_royale = Movie.objects.create(title="Casino Royale", year=2006, duration=144, director=martin_campbell)
Play.objects.create(movie=casino_royale, actor=daniel_craig, character="James Bond")

quantum = Movie.objects.create(title="Quantum of Solace", year=2008, duration=106, director=marc_forster)
Play.objects.create(movie=quantum, actor=daniel_craig, character="James Bond")

skyfall = Movie.objects.create(title="Skyfall", year=2012, duration=143, director=sam_mendes)
Play.objects.create(movie=skyfall, actor=daniel_craig, character="James Bond")

spectre = Movie.objects.create(title="Spectre", year=2015, duration=148, director=sam_mendes)
Play.objects.create(movie=spectre, actor=daniel_craig, character="James Bond")

no_time_to_die = Movie.objects.create(title="No Time to Die", year=2021, duration=163, director=cary_fukunaga)
Play.objects.create(movie=no_time_to_die, actor=daniel_craig, character="James Bond")

# Bond (ère classique)

sean_connery   = Person.objects.create(name="Sean Connery",   birthdate=date(1930,  8, 25), is_alive=False)
george_lazenby = Person.objects.create(name="George Lazenby", birthdate=date(1939,  9,  5))
roger_moore    = Person.objects.create(name="Roger Moore",    birthdate=date(1927, 10, 14), is_alive=False)
timothy_dalton = Person.objects.create(name="Timothy Dalton", birthdate=date(1944,  3, 21))
pierce_brosnan = Person.objects.create(name="Pierce Brosnan", birthdate=date(1953,  5, 16))

bernard_lee      = Person.objects.create(name="Bernard Lee",      birthdate=date(1908,  1, 10), is_alive=False)
lois_maxwell     = Person.objects.create(name="Lois Maxwell",     birthdate=date(1927,  2, 14), is_alive=False)
desmond_llewelyn = Person.objects.create(name="Desmond Llewelyn", birthdate=date(1914,  9, 12), is_alive=False)
robert_brown     = Person.objects.create(name="Robert Brown",     birthdate=date(1921,  3, 23), is_alive=False)
caroline_bliss   = Person.objects.create(name="Caroline Bliss",   birthdate=date(1961,  7,  9))
judi_dench       = Person.objects.create(name="Judi Dench",       birthdate=date(1934, 12,  9))
samantha_bond    = Person.objects.create(name="Samantha Bond",    birthdate=date(1961, 11, 27))

terence_young = Person.objects.create(name="Terence Young", birthdate=date(1915,  6, 20), is_alive=False)
peter_hunt    = Person.objects.create(name="Peter R. Hunt", birthdate=date(1925,  3, 11), is_alive=False)
lewis_gilbert = Person.objects.create(name="Lewis Gilbert", birthdate=date(1920,  3,  6), is_alive=False)
john_glen     = Person.objects.create(name="John Glen",     birthdate=date(1932,  5, 15))

ursula_andress = Person.objects.create(name="Ursula Andress",  birthdate=date(1936,  3, 19))
joseph_wiseman = Person.objects.create(name="Joseph Wiseman",  birthdate=date(1918,  5, 15), is_alive=False)
dr_no = Movie.objects.create(title="Dr. No", year=1962, duration=110, director=terence_young)
Play.objects.create(movie=dr_no, actor=sean_connery,   character="James Bond")
Play.objects.create(movie=dr_no, actor=ursula_andress, character="Honey Ryder")
Play.objects.create(movie=dr_no, actor=joseph_wiseman, character="Dr. No")
Play.objects.create(movie=dr_no, actor=bernard_lee,    character="M")
Play.objects.create(movie=dr_no, actor=lois_maxwell,   character="Moneypenny")

diana_rigg    = Person.objects.create(name="Diana Rigg",    birthdate=date(1938,  7, 20), is_alive=False)
telly_savalas = Person.objects.create(name="Telly Savalas", birthdate=date(1922,  1, 21), is_alive=False)
ohmss = Movie.objects.create(title="On Her Majesty's Secret Service", year=1969, duration=142, director=peter_hunt)
Play.objects.create(movie=ohmss, actor=george_lazenby, character="James Bond")
Play.objects.create(movie=ohmss, actor=diana_rigg,     character="Tracy Di Vicenzo")
Play.objects.create(movie=ohmss, actor=telly_savalas,  character="Blofeld")
Play.objects.create(movie=ohmss, actor=bernard_lee,    character="M")
Play.objects.create(movie=ohmss, actor=lois_maxwell,   character="Moneypenny")

barbara_bach = Person.objects.create(name="Barbara Bach",  birthdate=date(1947,  8, 27))
curt_jurgens = Person.objects.create(name="Curt Jurgens",  birthdate=date(1915, 12, 13), is_alive=False)
spy_loved_me = Movie.objects.create(title="The Spy Who Loved Me", year=1977, duration=125, director=lewis_gilbert)
Play.objects.create(movie=spy_loved_me, actor=roger_moore,       character="James Bond")
Play.objects.create(movie=spy_loved_me, actor=barbara_bach,      character="Anya Amasova")
Play.objects.create(movie=spy_loved_me, actor=curt_jurgens,      character="Karl Stromberg")
Play.objects.create(movie=spy_loved_me, actor=bernard_lee,       character="M")
Play.objects.create(movie=spy_loved_me, actor=desmond_llewelyn,  character="Q")

maryam_dabo   = Person.objects.create(name="Maryam d'Abo",  birthdate=date(1960, 12, 27))
jeroen_krabbe = Person.objects.create(name="Jeroen Krabbé", birthdate=date(1944, 10,  5))
living_day = Movie.objects.create(title="The Living Daylights", year=1987, duration=130, director=john_glen)
Play.objects.create(movie=living_day, actor=timothy_dalton,   character="James Bond")
Play.objects.create(movie=living_day, actor=maryam_dabo,      character="Kara Milovy")
Play.objects.create(movie=living_day, actor=jeroen_krabbe,    character="Georgi Koskov")
Play.objects.create(movie=living_day, actor=robert_brown,     character="M")
Play.objects.create(movie=living_day, actor=desmond_llewelyn, character="Q")

izabella_sc = Person.objects.create(name="Izabella Scorupco", birthdate=date(1970,  6,  4))
sean_bean   = Person.objects.create(name="Sean Bean",         birthdate=date(1959,  4, 17))
goldeneye = Movie.objects.create(title="GoldenEye", year=1995, duration=130, director=martin_campbell)
Play.objects.create(movie=goldeneye, actor=pierce_brosnan,    character="James Bond")
Play.objects.create(movie=goldeneye, actor=izabella_sc,       character="Natalya Simonova")
Play.objects.create(movie=goldeneye, actor=sean_bean,         character="Alec Trevelyan / 006")
Play.objects.create(movie=goldeneye, actor=judi_dench,        character="M")
Play.objects.create(movie=goldeneye, actor=desmond_llewelyn,  character="Q")

# Bond (ajouts acteurs récurrents sur films Craig)

ralph_fiennes   = Person.objects.create(name="Ralph Fiennes",   birthdate=date(1962, 12, 22))
ben_whishaw     = Person.objects.create(name="Ben Whishaw",     birthdate=date(1980, 10, 14))
naomie_harris   = Person.objects.create(name="Naomie Harris",   birthdate=date(1976,  9,  6))
jeffrey_wright  = Person.objects.create(name="Jeffrey Wright",  birthdate=date(1965, 12,  7))
christoph_waltz = Person.objects.create(name="Christoph Waltz", birthdate=date(1956, 10,  4))

Play.objects.create(movie=casino_royale, actor=judi_dench,     character="M")
Play.objects.create(movie=casino_royale, actor=jeffrey_wright,  character="Felix Leiter")

Play.objects.create(movie=quantum, actor=judi_dench,     character="M")
Play.objects.create(movie=quantum, actor=jeffrey_wright, character="Felix Leiter")

Play.objects.create(movie=skyfall, actor=judi_dench,    character="M")
Play.objects.create(movie=skyfall, actor=ralph_fiennes, character="Gareth Mallory / M")
Play.objects.create(movie=skyfall, actor=ben_whishaw,   character="Q")
Play.objects.create(movie=skyfall, actor=naomie_harris, character="Eve Moneypenny")

Play.objects.create(movie=spectre, actor=ralph_fiennes,   character="M")
Play.objects.create(movie=spectre, actor=ben_whishaw,     character="Q")
Play.objects.create(movie=spectre, actor=naomie_harris,   character="Moneypenny")
Play.objects.create(movie=spectre, actor=christoph_waltz, character="Ernst Stavro Blofeld")

Play.objects.create(movie=no_time_to_die, actor=ralph_fiennes,   character="M")
Play.objects.create(movie=no_time_to_die, actor=ben_whishaw,     character="Q")
Play.objects.create(movie=no_time_to_die, actor=naomie_harris,   character="Moneypenny")
Play.objects.create(movie=no_time_to_die, actor=jeffrey_wright,  character="Felix Leiter")
Play.objects.create(movie=no_time_to_die, actor=christoph_waltz, character="Ernst Stavro Blofeld")

# --- Scorsese / Cameron / Spielberg / Tarantino / Iñárritu ---

martin_scorsese  = Person.objects.create(name="Martin Scorsese",       birthdate=date(1942, 11, 17))
james_cameron    = Person.objects.create(name="James Cameron",         birthdate=date(1954,  8, 16))
steven_spielberg = Person.objects.create(name="Steven Spielberg",      birthdate=date(1946, 12, 18))
quentin_tt       = Person.objects.create(name="Quentin Tarantino",     birthdate=date(1963,  3, 27))
alejandro_gi     = Person.objects.create(name="Alejandro G. Iñárritu", birthdate=date(1963,  8, 15))

cate_blanchett  = Person.objects.create(name="Cate Blanchett",  birthdate=date(1969,  5, 14))
kate_beckinsale = Person.objects.create(name="Kate Beckinsale", birthdate=date(1973,  7, 26))
alec_baldwin    = Person.objects.create(name="Alec Baldwin",    birthdate=date(1958,  4,  3))
aviator = Movie.objects.create(title="The Aviator", year=2004, duration=170, director=martin_scorsese)
Play.objects.create(movie=aviator, actor=leo_dicaprio,    character="Howard Hughes")
Play.objects.create(movie=aviator, actor=cate_blanchett,  character="Katharine Hepburn")
Play.objects.create(movie=aviator, actor=kate_beckinsale, character="Ava Gardner")
Play.objects.create(movie=aviator, actor=alec_baldwin,    character="Juan Trippe")

jonah_hill    = Person.objects.create(name="Jonah Hill",    birthdate=date(1983, 12, 20))
margot_robbie = Person.objects.create(name="Margot Robbie", birthdate=date(1990,  7,  2))
wolf_wst = Movie.objects.create(title="The Wolf of Wall Street", year=2013, duration=180, director=martin_scorsese)
Play.objects.create(movie=wolf_wst, actor=leo_dicaprio,  character="Jordan Belfort")
Play.objects.create(movie=wolf_wst, actor=jonah_hill,    character="Donnie Azoff")
Play.objects.create(movie=wolf_wst, actor=margot_robbie, character="Naomi Lapaglia")

kate_winslet = Person.objects.create(name="Kate Winslet", birthdate=date(1975, 10,  5))
billy_zane   = Person.objects.create(name="Billy Zane",   birthdate=date(1966,  2, 24))
titanic = Movie.objects.create(title="Titanic", year=1997, duration=194, director=james_cameron)
Play.objects.create(movie=titanic, actor=leo_dicaprio, character="Jack Dawson")
Play.objects.create(movie=titanic, actor=kate_winslet, character="Rose DeWitt Bukater")
Play.objects.create(movie=titanic, actor=billy_zane,   character="Cal Hockley")

tom_hanks          = Person.objects.create(name="Tom Hanks",          birthdate=date(1956,  7,  9))
christopher_walken = Person.objects.create(name="Christopher Walken", birthdate=date(1943,  3, 31))
catch_me = Movie.objects.create(title="Catch Me If You Can", year=2002, duration=141, director=steven_spielberg)
Play.objects.create(movie=catch_me, actor=leo_dicaprio,       character="Frank Abagnale Jr.")
Play.objects.create(movie=catch_me, actor=tom_hanks,          character="Carl Hanratty")
Play.objects.create(movie=catch_me, actor=christopher_walken, character="Frank Abagnale Sr.")

jamie_foxx = Person.objects.create(name="Jamie Foxx",        birthdate=date(1967, 12, 13))
samuel_l_j = Person.objects.create(name="Samuel L. Jackson", birthdate=date(1948, 12, 21))
django_movie = Movie.objects.create(title="Django Unchained", year=2012, duration=165, director=quentin_tt)
Play.objects.create(movie=django_movie, actor=jamie_foxx,      character="Django Freeman")
Play.objects.create(movie=django_movie, actor=leo_dicaprio,    character="Calvin Candie")
Play.objects.create(movie=django_movie, actor=christoph_waltz, character="Dr. King Schultz")
Play.objects.create(movie=django_movie, actor=samuel_l_j,      character="Stephen")

domhnall_gleeson = Person.objects.create(name="Domhnall Gleeson", birthdate=date(1983,  5, 12))
will_poulter     = Person.objects.create(name="Will Poulter",     birthdate=date(1993,  1, 28))
revenant = Movie.objects.create(title="The Revenant", year=2015, duration=156, director=alejandro_gi)
Play.objects.create(movie=revenant, actor=leo_dicaprio,     character="Hugh Glass")
Play.objects.create(movie=revenant, actor=tom_hardy,        character="John Fitzgerald")
Play.objects.create(movie=revenant, actor=domhnall_gleeson, character="Andrew Henry")
Play.objects.create(movie=revenant, actor=will_poulter,     character="Jim Bridger")

# --- American Psycho ---

mary_harron   = Person.objects.create(name="Mary Harron",        birthdate=date(1953,  1, 12))
jared_leto    = Person.objects.create(name="Jared Leto",         birthdate=date(1971, 12, 26))
willem_dafoe  = Person.objects.create(name="Willem Dafoe",       birthdate=date(1955,  7, 22))
reese_withers = Person.objects.create(name="Reese Witherspoon",  birthdate=date(1976,  3, 22))
american_psycho = Movie.objects.create(title="American Psycho", year=2000, duration=102, director=mary_harron)
Play.objects.create(movie=american_psycho, actor=christian_bale, character="Patrick Bateman")
Play.objects.create(movie=american_psycho, actor=jared_leto,     character="Paul Allen")
Play.objects.create(movie=american_psycho, actor=willem_dafoe,   character="Donald Kimball")
Play.objects.create(movie=american_psycho, actor=reese_withers,  character="Evelyn Williams")

# --- Rian Johnson ---

rian_johnson = Person.objects.create(name="Rian Johnson", birthdate=date(1973, 12, 17))

ana_de_armas     = Person.objects.create(name="Ana de Armas",       birthdate=date(1988,  4, 30))
chris_evans      = Person.objects.create(name="Chris Evans",        birthdate=date(1981,  6, 13))
jamie_lee_curtis = Person.objects.create(name="Jamie Lee Curtis",   birthdate=date(1958, 11, 22))
christopher_plum = Person.objects.create(name="Christopher Plummer",birthdate=date(1929, 12, 13), is_alive=False)
knives_out = Movie.objects.create(title="Knives Out", year=2019, duration=131, director=rian_johnson)
Play.objects.create(movie=knives_out, actor=daniel_craig,     character="Benoit Blanc")
Play.objects.create(movie=knives_out, actor=ana_de_armas,     character="Marta Cabrera")
Play.objects.create(movie=knives_out, actor=chris_evans,      character="Ransom Drysdale")
Play.objects.create(movie=knives_out, actor=jamie_lee_curtis, character="Linda Drysdale")
Play.objects.create(movie=knives_out, actor=christopher_plum, character="Harlan Thrombey")

edward_norton = Person.objects.create(name="Edward Norton",  birthdate=date(1969,  8, 18))
janelle_monae = Person.objects.create(name="Janelle Monáe",  birthdate=date(1985, 12,  1))
kate_hudson   = Person.objects.create(name="Kate Hudson",    birthdate=date(1979,  4, 19))
dave_bautista = Person.objects.create(name="Dave Bautista",  birthdate=date(1969,  1, 18))
glass_onion = Movie.objects.create(title="Glass Onion", year=2022, duration=139, director=rian_johnson)
Play.objects.create(movie=glass_onion, actor=daniel_craig,  character="Benoit Blanc")
Play.objects.create(movie=glass_onion, actor=edward_norton, character="Miles Bron")
Play.objects.create(movie=glass_onion, actor=janelle_monae, character="Andi Brand / Helen Brand")
Play.objects.create(movie=glass_onion, actor=kate_hudson,   character="Birdie Jay")
Play.objects.create(movie=glass_onion, actor=dave_bautista, character="Duke Cody")

glenn_close   = Person.objects.create(name="Glenn Close",   birthdate=date(1947,  3, 19))
josh_brolin   = Person.objects.create(name="Josh Brolin",   birthdate=date(1968,  2, 12))
mila_kunis    = Person.objects.create(name="Mila Kunis",    birthdate=date(1983,  8, 14))
jeremy_renner = Person.objects.create(name="Jeremy Renner", birthdate=date(1971,  1,  7))
josh_oconnor  = Person.objects.create(name="Josh O'Connor", birthdate=date(1990,  5, 20))
wake_up = Movie.objects.create(title="Wake Up Dead Man", year=2025, duration=144, director=rian_johnson)
Play.objects.create(movie=wake_up, actor=daniel_craig,  character="Benoit Blanc")
Play.objects.create(movie=wake_up, actor=glenn_close,   character="Martha Delacroix")
Play.objects.create(movie=wake_up, actor=josh_brolin,   character="M. Jefferson Wicks")
Play.objects.create(movie=wake_up, actor=mila_kunis,    character="Chief Geraldine Scott")
Play.objects.create(movie=wake_up, actor=jeremy_renner, character="Dr. Nat Sharp")
Play.objects.create(movie=wake_up, actor=josh_oconnor,  character="Fr. Jud Duplenticy")

# --- Clint Eastwood ---

clint_eastwood = Person.objects.create(name="Clint Eastwood", birthdate=date(1930,  5, 31))
sergio_leone   = Person.objects.create(name="Sergio Leone",   birthdate=date(1929,  1,  3), is_alive=False)
don_siegel     = Person.objects.create(name="Don Siegel",     birthdate=date(1912, 10, 26), is_alive=False)

lee_van_cleef = Person.objects.create(name="Lee Van Cleef", birthdate=date(1925,  1,  9), is_alive=False)
eli_wallach   = Person.objects.create(name="Eli Wallach",   birthdate=date(1915, 12,  7), is_alive=False)
gbu = Movie.objects.create(title="Le Bon, la Brute et le Truand", year=1966, duration=161, director=sergio_leone)
Play.objects.create(movie=gbu, actor=clint_eastwood, character="Blondie / Le Bon")
Play.objects.create(movie=gbu, actor=lee_van_cleef,  character="Angel Eyes / Le Truand")
Play.objects.create(movie=gbu, actor=eli_wallach,    character="Tuco / La Brute")

andy_robinson = Person.objects.create(name="Andy Robinson", birthdate=date(1942,  2, 14))
dirty_harry = Movie.objects.create(title="L'Inspecteur Harry", year=1971, duration=102, director=don_siegel)
Play.objects.create(movie=dirty_harry, actor=clint_eastwood, character="Harry Callahan")
Play.objects.create(movie=dirty_harry, actor=andy_robinson,  character="Scorpio")

gene_hackman   = Person.objects.create(name="Gene Hackman",   birthdate=date(1930,  1, 30), is_alive=False)
morgan_freeman = Person.objects.create(name="Morgan Freeman", birthdate=date(1937,  6,  1))
richard_harris = Person.objects.create(name="Richard Harris", birthdate=date(1930, 10,  1), is_alive=False)
unforgiven = Movie.objects.create(title="Impitoyable", year=1992, duration=130, director=clint_eastwood)
Play.objects.create(movie=unforgiven, actor=clint_eastwood, character="William Munny")
Play.objects.create(movie=unforgiven, actor=gene_hackman,   character="Little Bill Daggett")
Play.objects.create(movie=unforgiven, actor=morgan_freeman, character="Ned Logan")
Play.objects.create(movie=unforgiven, actor=richard_harris, character="English Bob")

bee_vang  = Person.objects.create(name="Bee Vang",  birthdate=date(1992,  5, 25))
ahney_her = Person.objects.create(name="Ahney Her", birthdate=date(1991, 11, 16))
gran_torino = Movie.objects.create(title="Gran Torino", year=2008, duration=116, director=clint_eastwood)
Play.objects.create(movie=gran_torino, actor=clint_eastwood, character="Walt Kowalski")
Play.objects.create(movie=gran_torino, actor=bee_vang,       character="Thao")
Play.objects.create(movie=gran_torino, actor=ahney_her,      character="Sue")

nicholas_hoult = Person.objects.create(name="Nicholas Hoult", birthdate=date(1989, 12,  7))
toni_collette  = Person.objects.create(name="Toni Collette",  birthdate=date(1972, 11,  1))
jk_simmons     = Person.objects.create(name="J.K. Simmons",   birthdate=date(1955,  1,  9))
jure2 = Movie.objects.create(title="Juré n°2", year=2024, duration=114, director=clint_eastwood)
Play.objects.create(movie=jure2, actor=nicholas_hoult, character="Justin Kemp")
Play.objects.create(movie=jure2, actor=toni_collette,  character="Faith Killebrew")
Play.objects.create(movie=jure2, actor=jk_simmons,     character="Harold")

# --- Steve McQueen ---

steve_mcqueen_actor = Person.objects.create(name="Steve McQueen", birthdate=date(1930,  3, 24), is_alive=False)
steve_mcqueen_dir   = Person.objects.create(name="Steve McQueen", birthdate=date(1969, 10,  9))

john_sturges = Person.objects.create(name="John Sturges", birthdate=date(1910,  1,  3), is_alive=False)
peter_yates  = Person.objects.create(name="Peter Yates",  birthdate=date(1929,  7, 24), is_alive=False)

james_garner      = Person.objects.create(name="James Garner",         birthdate=date(1928,  4,  7), is_alive=False)
richard_attenboro = Person.objects.create(name="Richard Attenborough", birthdate=date(1923,  8, 29), is_alive=False)
great_escape = Movie.objects.create(title="La Grande Évasion", year=1963, duration=172, director=john_sturges)
Play.objects.create(movie=great_escape, actor=steve_mcqueen_actor, character="Virgil Hilts")
Play.objects.create(movie=great_escape, actor=james_garner,        character="Bob Hendley")
Play.objects.create(movie=great_escape, actor=richard_attenboro,   character="Roger Bartlett")

robert_vaughn = Person.objects.create(name="Robert Vaughn",     birthdate=date(1932, 11, 22), is_alive=False)
jacqueline_b  = Person.objects.create(name="Jacqueline Bisset", birthdate=date(1944,  9, 13))
bullitt = Movie.objects.create(title="Bullitt", year=1968, duration=114, director=peter_yates)
Play.objects.create(movie=bullitt, actor=steve_mcqueen_actor, character="Frank Bullitt")
Play.objects.create(movie=bullitt, actor=robert_vaughn,       character="Walter Chalmers")
Play.objects.create(movie=bullitt, actor=jacqueline_b,        character="Cathy")

michael_fassbender = Person.objects.create(name="Michael Fassbender", birthdate=date(1977,  4,  2))
carey_mulligan     = Person.objects.create(name="Carey Mulligan",     birthdate=date(1985,  5, 28))
shame = Movie.objects.create(title="Shame", year=2011, duration=101, director=steve_mcqueen_dir)
Play.objects.create(movie=shame, actor=michael_fassbender, character="Brandon Sullivan")
Play.objects.create(movie=shame, actor=carey_mulligan,     character="Sissy Sullivan")

viola_davis   = Person.objects.create(name="Viola Davis",        birthdate=date(1965,  8, 11))
michelle_rod  = Person.objects.create(name="Michelle Rodriguez", birthdate=date(1978,  7, 12))
colin_farrell = Person.objects.create(name="Colin Farrell",      birthdate=date(1976,  5, 31))
widows = Movie.objects.create(title="Widows", year=2018, duration=129, director=steve_mcqueen_dir)
Play.objects.create(movie=widows, actor=viola_davis,   character="Veronica Rawlings")
Play.objects.create(movie=widows, actor=michelle_rod,  character="Linda")
Play.objects.create(movie=widows, actor=elizabeth_d,   character="Alice")
Play.objects.create(movie=widows, actor=colin_farrell, character="Jack Mulligan")

# --- récap ---
person_count = Person.objects.count()
movie_count = Movie.objects.count()
play_count = Play.objects.count()
print(f"Person : {person_count}")
print(f"Movie  : {movie_count}")
print(f"Play   : {play_count}")
