# Generated by Django 5.2.12 on 2026-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
