# Generated by Django 5.2.12 on 2026-05-05 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_people', '0002_person_is_alive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='app_people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_people.person')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_movie.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='played_movies', through='app_movie.Play', through_fields=('movie', 'actor'), to='app_people.person'),
        ),
    ]
