# Generated by Django 5.2.12 on 2026-05-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0001_initial'),
        ('app_people', '0002_person_is_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='app_people.person'),
        ),
        migrations.AlterField(
            model_name='play',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='app_movie.movie'),
        ),
    ]
