# Generated by Django 5.2.12 on 2026-05-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0002_alter_play_actor_alter_play_movie'),
        ('app_people', '0002_person_is_alive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='play',
            unique_together={('movie', 'actor', 'character')},
        ),
    ]
